RPI_LOOP_INTERVAL = 0.1  # in second
RPI_SERIAL = {'port': '/dev/ttyS0'}
RPI_START_DISTANCE = 0.1  # in meter

TEST_START_DEGREE = 0.5
TEST_START_DISTANCE = 0.1

INTERRUPT_INST_SHOW_RESULT = 0
INTERRUPT_INST_WAIT_MOV = 1
INTERRUPT_INST_START_MOV = 2
INTERRUPT_INST_SHOW_IMG = 3
INTERRUPT_INST_GET_RESP = 4

INTERRUPT_RESULT_MIN = -1.0
INTERRUPT_RESULT_MAX = 2.0
